# Site setup
title: rtxti
description: rtxti website

url: https://rtxti.github.io
baseurl: /www

permalink: pretty

timezone: Asia/Jakarta

sass:
  sass_dir: _sass
  style: :compressed
  
collections:
  smartphones:
    output: true

author:
  name: rtxti
  email: rtxti@outlook.com
  
version: 1.0.0
